{{- if .Values.env.configMapRef.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.service }}-config"
  labels:
    app.kubernetes.io/name: {{ .Values.service | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
{{- range $key, $value := .Values.env.configMapRef.values }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}