{{- if .Values.migrate.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ (print .Values.service "-migrate-v" .Values.version "-") | quote }}
  annotations:
    app.kubernetes.io/name: {{ .Values.service | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
  namespace: {{ .Release.namespace | quote }}
spec:
  template:
    metadata:
      name: {{ (print .Values.service "-migrate-v" .Values.version) | quote }}
      annotations: 
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ (print .Values.service "-migrate") | quote }}
        image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}"
        imagePullPolicy: Always
        args: ["-user=${DB_USERNAME}", "-password=${DB_PASSWORD}", "-url=${MIGRATE_URL}", "migrate"]
        env:
          - name: DB_USERNAME
            value: {{ .Values.env.configMapRef.values.DB_USERNAME | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.env.secretRef.values.DB_PASSWORD | quote }}
          - name: MIGRATE_URL
            value: {{ .Values.env.configMapRef.values.MIGRATE_URL | quote }}
{{- end }}
