{{- if .Values.migrate.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ (print .Values.service "-migrate-v" .Values.version) | quote }}
  annotations:
    app.kubernetes.io/name: {{ .Values.service | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
  namespace: {{ .Release.namespace | quote }}
spec:
  template:
    metadata:
      name: {{ (print .Values.service "-migrate-v" .Values.version) | quote }}
      annotations: 
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ (print .Values.service "-migrate") | quote }}
        image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}"
        imagePullPolicy: Always
        args: ["migrate"]
        env:
          - name: DB_USERNAME
            value: {{ .Values.env.migratorConfigMapRef.values.DB_USERNAME | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.env.migratorConfigMapRef.values.DB_PASSWORD | quote }}
          - name: MIGRATE_URL
            value: {{ .Values.env.migratorConfigMapRef.values.MIGRATE_URL | quote }}
          - name: DD_ENV
            value: |-
              {{ $.Release.Namespace }}
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_TAGS
            value: |-
              app:{{ (print .Values.service "-migrate") }},env:{{ $.Release.Namespace }},part-of:{{ .Values.system }}
          - name: DD_TRACE_ANALYTICS_ENABLED
            value: "true"
          - name: DD_TRACE_ENABLED
            value: "true"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
{{- end }}
