{{- if .Values.env.secretRef.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.service }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.service | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
{{- range $key, $val := .Values.env.secretRef.values }}
  {{ $key }}: {{ $val| b64enc }}
{{- end }}
{{- end }}