{{- range .Values.env.secretRef }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
{{- range $key, $val := .content }}
  {{ $key }}: ${{ val }}
{{- end }}
{{- end }}
